package com.medical.gemini;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.medical.exception.BadRequestException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
@RequiredArgsConstructor
@Slf4j
public class GeminiService {

    private static final String PROMPT = """
You are an expert medical report summarizer.

Analyze the following medical report.

Return ONLY valid JSON.

{
  "summary": "",
  "medicalConditions": [],
  "medications": [],
  "labResults": [],
  "doctorRecommendations": "",
  "riskFactors": [],
  "followUp": "",
  "importantNotes": []
}

Rules:
- Return only JSON.
- No markdown.
- No explanation.
- If information is missing use:
  "" for strings
  [] for arrays.
""";

    private static final Pattern JSON_PATTERN = Pattern.compile("\\{.*\\}", Pattern.DOTALL);

    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    public GeminiSummaryResult generateSummary(String reportText) {
        if (reportText == null || reportText.isBlank()) {
            throw new BadRequestException("Report text is empty. Cannot generate summary.");
        }

        String truncatedText = reportText.length() > 30000
                ? reportText.substring(0, 30000)
                : reportText;

        try {
            Map<String, Object> requestBody = buildRequestBody(truncatedText);
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            String url = apiUrl + "?key=" + apiKey;
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);

            ResponseEntity<String> response = restTemplate.exchange(
                    url, HttpMethod.POST, entity, String.class);

            if (!response.getStatusCode().is2xxSuccessful() || response.getBody() == null) {
                throw new BadRequestException("Failed to get response from Gemini API");
            }

            String jsonContent = extractJsonFromResponse(response.getBody());
            return objectMapper.readValue(jsonContent, GeminiSummaryResult.class);
        } catch (BadRequestException e) {
            throw e;
        } catch (Exception e) {
            log.error("Gemini API error: {}", e.getMessage(), e);
            throw new BadRequestException("Failed to generate summary: " + e.getMessage());
        }
    }

    private Map<String, Object> buildRequestBody(String reportText) {
        Map<String, Object> textPart = Map.of("text", PROMPT + "\n\nMedical Report:\n" + reportText);
        Map<String, Object> content = Map.of("parts", List.of(textPart));
        Map<String, Object> generationConfig = Map.of(
                "temperature", 0.2,
                "responseMimeType", "application/json"
        );

        Map<String, Object> body = new HashMap<>();
        body.put("contents", List.of(content));
        body.put("generationConfig", generationConfig);
        return body;
    }

    private String extractJsonFromResponse(String responseBody) throws Exception {
        JsonNode root = objectMapper.readTree(responseBody);
        JsonNode candidates = root.path("candidates");
        if (candidates.isEmpty()) {
            throw new BadRequestException("No summary generated by Gemini");
        }

        String text = candidates.get(0)
                .path("content")
                .path("parts")
                .get(0)
                .path("text")
                .asText();

        Matcher matcher = JSON_PATTERN.matcher(text);
        if (matcher.find()) {
            return matcher.group();
        }
        return text.trim();
    }
}
